services:
  - type: web
    name: brightstart-backend
    runtime: docker
    plan: free
    region: frankfurt

    rootDir: backendBrightStart-master
    dockerfilePath: ./Dockerfile

    healthCheckPath: /actuator/health

    envVars:

      # ==========================================
      # SUPABASE DATABASE
      # ==========================================

      - key: DATABASE_URL
        sync: false

      - key: DATABASE_USERNAME
        sync: false

      - key: DATABASE_PASSWORD
        sync: false


      # ==========================================
      # JWT
      # ==========================================

      - key: JWT_SECRET
        sync: false
