
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.gncxjmrkzctolsybepht&password=[BrightStart@PrP]
spring.datasource.username=postgres.gncxjmrkzctolsybepht
spring.datasource.password=BrightStart@PrP
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=false

server.port=5432

jwt.secret=StandardCharsets.UTF_8
jwt.expiration=86400000


